### PR TITLE
added RELEASE_DATES

### PR DESCRIPTION
**Pull request by thinkingmedia**
Movie "releases" is now deprecated. The API will still return results for it, but the data is no longer being updated. So it can contain incorrect data.

People should be using "release_dates" instead as it contains release type, and is also being updated now.

This PR adds the release_dates append_to_response constant.

### CODE REVIEW

**Comment by drone-ah** [comment]
Hi,

I have added a commit in the following branch to add getters/setters for release_dates within the movie model
https://github.com/drone-ah/api/tree/release_dates

HTH,

Shri

**Comment by thinkingmedia** [comment]
@drone-ah thanks for the improvement.

I don't think that change is consistent with how the library handles properties of a movie. I'll take a look and see if I can fix it.

Thanks,

**Comment by thinkingmedia** [comment]
I've added a new ReleaseDate and update Movies. I still need to add tests for these new changes.

**Comment by drone-ah** [comment]
@thinkingmedia Thank you :)

**Comment by drone-ah** [comment]
@thinkingmedia I have picked up your latest code. In this, you have deprecated getReleaseDates() suggesting to use getReleaseDates instead. I assume this is a mistake and this method shouldn't be deprecated. If this is correct, perhaps the comment could be clearer?

Thanks

**Comment by thinkingmedia** [comment]
@drone-ah I haven't actually tried these changes yet. Is it working for you?

I'm unable to run phpunit for some reason. So I opened this issue #141 and maybe I can get some help with that. Once that is working I can update the tests and this can get merged.

**Comment by wtfzdotnet** [comment]
@thinkingmedia rebase on the 2.1 branch and push your commits again :), I have restricted the phpunit version to <6

**Comment by thinkingmedia** [comment]
@wtfzdotnet  Awesome, the tests are working now. thank you!

I'll add some more tests now.

**Comment by wtfzdotnet** [comment]
Could you give it another rebase? Just modified the travis.yml to make sure it is tested against symfony 3.2.* components. Give me a heads up when you feel like it's done for review.

**Comment by thinkingmedia** [comment]
@wtfzdotnet okay, I'm finished. Travis should pass but we can wait to be sure.

**Comment by thinkingmedia** [comment]
@wtfzdotnet ping

**Comment by wtfzdotnet** [comment]
@thinkingmedia I'm really assuming all is good here, time is really really sparse for me lately and I'm going to be busy until next week again. Just pushing a quick release out now!

**Comment by thinkingmedia** [comment]
@wtfzdotnet everything is good!

If you are that busy. How about inviting me to me a member? I can help with closing issues.

**Pull request merged**
