### PR TITLE
Allow symfony 5 components

### PR DESCRIPTION
**Pull request by DariusIII**
Allow usage of Symfony 5 components.

### CODE REVIEW

**Review by wtfzdotnet — APPROVED** [review]

**Comment by wtfzdotnet** [comment]
@DariusIII could you also update the `.travis.yml` just to confirm the tests don't die?

**Review by wtfzdotnet — CHANGES_REQUESTED** [review]
^

**Comment by DariusIII** [comment]
Sure, i will.

**Comment by DariusIII** [comment]
Could support for older symfony versions and php be dropped? Just asking.

**Comment by wtfzdotnet** [comment]
Preferably keep symfony LTS, with recent versions and just drop < 7.2, but I think that would require a major release to keep everybody happy :-)

**Comment by DariusIII** [comment]
Issue is that path to EventDispatcher/Event has changed in newer versions. 
I agree new major version should be made. 
I am doing this from github directly, but i think i need to pull it into PHPStorm and work from there properly, to prevent issues i have now - checking if travis will fail or not and then changing things.

**Comment by wtfzdotnet** [comment]
I'll try and see if I can get this merged into a new `3.0` version (hopefully today), have had discussions with somebody else about doing a rewrite, and put that attention towards `4.0`.

**Comment by DariusIII** [comment]
@wtfzdotnet 

Great, looking forward to it. :)

**Comment by wtfzdotnet** [comment]
@DariusIII slight delay on my end, sorry! :-) let me know if 3.0 does it's magic well

**Comment by DariusIII** [comment]
@wtfzdotnet Will test and report back. Thank you!

**Pull request merged**
