### PR TITLE
Fixed Episode and Season Repositories

### PR DESCRIPTION
**Pull request by geochatz**
Episode and Season API use the Season Number and Episode Number and not their id to fetch data. 

Also changed the check with the is_null function in the load function as there is a chance
that there is a Season 0 for a TV Show. When the Season is 0 then the
$season == null returns true.

### CODE REVIEW

**Comment by wtfzdotnet** [comment]
@geochatz, could you update the pr with passing unit tests?

**Comment by geochatz** [comment]
I fixed that. The PR now passes all tests :)

**Comment by wtfzdotnet** [comment]
I'll try and check tomorrow :)

**Comment by wtfzdotnet** [comment]
Thanks @geochatz ! :) I have not been using this library in years actively, so some extra help maintaining it would be appreciated!

**Comment by geochatz** [comment]
No problem. I am currently using it so it's easy for me to test it ;)

I also created another pull request with a small issue.

**Pull request merged**
